### ISSUE TITLE
how did you disable the dgpu 

### ISSUE THREAD

**Issue by UsetUset2244** [Forte500/Hackintosh-msi-GF65-10UE#1]
i have the same laptop i couldnt know how to do it

**Comment by Forte500** [comment]
I've used [SSDT-dGPU-Off (Optimus Method)](https://dortania.github.io/Getting-Started-With-ACPI/Laptops/laptop-disable.html#optimus-method) as the guide says.

Btw I have doubts about whether the gpu is actually turned off because the laptop seems to consume a lot of power but it's a problem I'm still diagnosing so I can't say for sure.

**Comment by UsetUset2244** [comment]
im on linux cant do this unfortunntily :(

**Comment by Forte500** [comment]
just use the ssdt from my efi, or download the template from the opencore guide, since it's an nvidia card I don't feel like I touched anything, it was already fine, but I'm not sure

**Comment by UsetUset2244** [comment]
oh ok
